apiVersion: versionlens.com/v1
kind: Version

# k8s metadata
metadata:
  name: version-store--main--copper-alien

# need to have metadata
customerCompany: "version-store"
project: "main"
versionName: "copper-alien"

# git clone
versionRepository: "https://github.com/VersionLens/version-store-version-repository.git"
versionRepositoryCommit: "5e7eb3acca23ba94a04d77a43312e90a95a2212c"

# argocd
destinationClusterName: "version-store"

# parameters
params:
  version-store-frontend:
    VERSION_STORE_FRONTEND_SHA: ff58cc556269ede04ef6045465aafb2ed5747903
  version-store-backend:
    VERSION_STORE_BACKEND_SHA: 142b56b046d32eef4dc159359cb29d54a4c02b98
